### PR TITLE
Update videolectures.py

### PR DESCRIPTION
**Pull request by priyambj**
- Updates to resolve error for bio attribute in Bio object.
- Updated categories fetched based on the complete chain of tags.

### CODE REVIEW

**Comment by lfierro** [comment]
Hi Priya. 
A few issues:
1) extra space that causes indention problems "scraper/erudite_schema.py", line 399
2) extra tab causing indentation problems "scraper/website/bigdatauniversity.py", line 180
3) mix of tabs and spaces being used for the get_bio function causing running problems
4) indentation issue at "/tmp/erudite/scraper/website/videolectures.py", line 96
5) It looks like the categories are not captured for the resources? 
6) The providers in the works_for table should be captured in a providers table

Are you using an IDE to write and edit these scripts, Priya? I was using Canopy before, but I'm a new convert to PyCharm. Either way, any Python IDE will help with debugging the indentation issues.

**Comment by priyambj** [comment]
Hi Lily,
Good evening,

I am using LiClipse IDE for debugging, I will look into the indentation
issues.

5) Categories of resources :

     1) Videolecture - I have scrapped each row as one category and
assigned to the resource. For reference please find the          csv file
attached and let me know the required changes to be made.

     2) Bigdatauniversity -  The courses are categorized into one single
domain. No specific one mentioned for each of them.

Although we are having a set of course learning path, comprising the
courses the resource is part of. I have stored the information in the
part_of relation.

6) Noted, will add the provider object in vidoelecture script.


Please let me know if you face any issues apart from these.
Also we can discuss on hangout session, whenever you are available.

Thanks
Priyambada





On Tue, Nov 8, 2016 at 3:59 PM, lfierro <notifications@github.com> wrote:

> Hi Priya.
> A few issues:
> 1) extra space that causes indention problems "scraper/erudite_schema.py",
> line 399
> 2) extra tab causing indentation problems "scraper/website/bigdatauniversity.py",
> line 180
> 3) mix of tabs and spaces being used for the get_bio function causing
> running problems
> 4) indentation issue at "/tmp/erudite/scraper/website/videolectures.py",
> line 96
> 5) It looks like the categories are not captured for the resources?
> 6) The providers in the works_for table should be captured in a providers
> table
>
> Are you using an IDE to write and edit these scripts, Priya? I was using
> Canopy before, but I'm a new convert to PyCharm. Either way, any Python IDE
> will help with debugging the indentation issues.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_BMKEG_erudite-2Dpy_pull_7-23issuecomment-2D259298172&d=DgMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=-QEWuN9XPGPBX-CA4TPBTg&m=wcq2ZqjdHhJJLx4Jd5h9ZPst8-GyHz5rO8S-sGNS2A0&s=X6pqjyg8Kys8X_elHoeOU3H2iSMBGUH5EXHFNba_L10&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AUDjKlJyLU0rsX-5FrB2hT-5FspMH6krFJ-2DMks5q8QzegaJpZM4Ks5qc&d=DgMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=-QEWuN9XPGPBX-CA4TPBTg&m=wcq2ZqjdHhJJLx4Jd5h9ZPst8-GyHz5rO8S-sGNS2A0&s=VgguyVY5euLMDAtXMGozkv8hMNjhAAbeuCRi5UjLQ9k&e=>
> .
>



-- 
USC Viterbi School of Engineering | M.S Computer Science
Computer Science Department Senator, Viterbi Graduate Student Association
USC Information Sciences Institute  | Student Worker - Programmer
LinkedIn | +1-213-421-4495 <http://none>

**Comment by lfierro** [comment]
Thanks Priya! Regarding categories: the BigDataU Categories/Paths makes sense. I should have clarified; after running the script for videolectures.net alone, I did not get the part_of CSV for the videolectures resources, which is where you are storing the categories, correct? Let's speak over Hangouts tomorrow.

**Comment by priyambj** [comment]
Thanks Lily,
For Videolectures.net as the categories were subjected to the tags, so the
relation has_subject contains all the mapping for the corresponding
categories with the resources.
The reason for mapping it in the relation was due to the fact that part_of
relation consists of all the courses that are part of resource.
Let me know if the mapping is inconsistent. Sure! Let discuss it tomorrow
for further clarifications.

Thanks
Priyambada

**Comment by priyambj** [comment]
Hi Lily,
Please review the updates.

Thanks

**Comment by lfierro** [comment]
Going to close this request until code is fully updated and ready for a merge.

**Pull request closed without merging**
